# Generated by Django 4.2.11 on 2024-04-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyixa', '0002_maxsulot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapchast',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
